### ISSUE TITLE
我的产品型号是Hanshow Nowa 213R-N，直接用文件里编译好的固件，可以正常显示，但是分辨率不对，左边会有大概50个像素显示不出来，尝试按照你的方法修改 0x44 0x45 0x24 0x26编辑分辨率，发现分辨率改完以后会花屏，并且仍然会显示不全，后来经过尝试，你的源码原封不动，直接编译，不管是在Windows\Linux平台下，也是一样的情况，不知道问题出在哪里！

### ISSUE THREAD

**Issue by QQ121142693** [reece15/stellar-L3N-etag#2]
我的产品型号是Hanshow Nowa 213R-N，直接用文件里编译好的固件，可以正常显示，但是分辨率不对，左边会有大概50个像素显示不出来，尝试按照你的方法修改 0x44 0x45 0x24 0x26编辑分辨率，发现分辨率改完以后会花屏，并且仍然会显示不全，后来经过尝试，你的源码原封不动，直接编译，不管是在Windows\Linux平台下，也是一样的情况，不知道问题出在哪里！

**Comment by reece15** [comment]
@QQ121142693 
1. 你可能需要先确定你的设备是否正常，可以通过web图片上传工具，清空屏幕为黑或者白，来查看屏幕是否正常。
2. 可以上传几张有明确参照物的图片（比如四个角画上不同的数字），看看是否屏幕的内存坐标是否和你期望的一样。
3. 可以尝试原作者的固件，原作者的固件是2.13寸的

**Comment by amilys** [comment]
汉朔L3N 板型:HS_EL5102_9M_61_01
串口刷入固件闪蓝灯，但是刷完屏幕无反应

**Comment by huang-li-hui** [comment]
> 我的产品型号是Hanshow Nowa 213R-N，直接用文件里编译好的固件，可以正常显示，但是分辨率不对，左边会有大概50个像素显示不出来，尝试按照你的方法修改 0x44 0x45 0x24 0x26编辑分辨率，发现分辨率改完以后会花屏，并且仍然会显示不全，后来经过尝试，你的源码原封不动，直接编译，不管是在Windows\Linux平台下，也是一样的情况，不知道问题出在哪里！

我和你是同一个型号，可否将你的修改版分享给我，谢谢
