### ISSUE TITLE
请教蓝牙更新图片的命令协议和格式

### ISSUE THREAD

**Issue by HapCoderWei** [reece15/stellar-L3N-etag#4]
大佬你好，我正在自己魔改一个2.13的价签，主控也是tlsr8359.发现你的这个项目完成度很高，想尽量复用你这个项目进行适配。对你的项目的代码有几个地方有点没太看懂，希望能得到大佬解答，非常感谢！

1.我看项目中更新图片之前都有先发送0000和020000这2个数字，但是在8359的代码中没有太看懂处理这2个数字的代码逻辑是哪里，希望大佬能解答一下；
2.在8359代码中处理蓝牙数据的方法应该是这个“epd_ble_handle_write”，但是这个方法中对payload数组的使用没太看懂，请问上位机发送的蓝牙数据中是如何被拆分成payload数组的，在一次接收数据时，payload中的数据格式和上位机发送的数据时如何对应上的，希望大佬能说明一下，我在8359的sdk中也没有找到这部分代码的使用说明；
3.我适配的价签屏幕是2.13寸，我想在您的web工具基础上给价签传输250*128的图片，是不是直接修改网页中图片的width和height就可以了；

大佬做的太强了，还在原项目的基础上实现了3色模式，从你的代码中也学到了很多东西，再次感谢大佬的开源和工作，大佬牛皮！

**Comment by reece15** [comment]
- 代码位置：https://github.com/reece15/stellar-L3N-etag/blob/main/Firmware/src/app_att.c#L202
- 最终调用位置：https://github.com/reece15/stellar-L3N-etag/blob/main/Firmware/src/epd_ble_service.c#L34

**Comment by HapCoderWei** [comment]
大佬你提供的2个位置我都看到了，我自己的问题是没有明白程序是如何对电脑发送的数据进行处理的。
https://github.com/reece15/stellar-L3N-etag/blob/main/Firmware/src/epd_ble_service.c#L34 这里的代码我是这样理解的，在tlsr8359每次收到数据的时候都会根据收到数据的第一个字节来匹配要执行什么样的逻辑。然后浏览器中更新图片之前都有先发送0000和020000这2个数字，那么按照这里的代码逻辑：
```
switch (payload[0])
	{
	// Clear EPD display.
	case 0x00:
	    ASSERT_MIN_LEN(payload_len, 2);
		memset(epd_buffer, payload[1], epd_buffer_size);
		memset(epd_temp, payload[1], epd_buffer_size);
		ble_set_connection_speed(40);
		return 0;
```
payload[1]应该等于00，没有看到8359解析收到的图片数据的逻辑。不知道我这样理解对不对，希望大佬能指导一下😂

**Comment by reece15** [comment]
> 大佬你提供的2个位置我都看到了，我自己的问题是没有明白程序是如何对电脑发送的数据进行处理的。 https://github.com/reece15/stellar-L3N-etag/blob/main/Firmware/src/epd_ble_service.c#L34 这里的代码我是这样理解的，在tlsr8359每次收到数据的时候都会根据收到数据的第一个字节来匹配要执行什么样的逻辑。然后浏览器中更新图片之前都有先发送0000和020000这2个数字，那么按照这里的代码逻辑：
> 
> ```
> switch (payload[0])
> 	{
> 	// Clear EPD display.
> 	case 0x00:
> 	    ASSERT_MIN_LEN(payload_len, 2);
> 		memset(epd_buffer, payload[1], epd_buffer_size);
> 		memset(epd_temp, payload[1], epd_buffer_size);
> 		ble_set_connection_speed(40);
> 		return 0;
> ```
> 
> payload[1]应该等于00，没有看到8359解析收到的图片数据的逻辑。不知道我这样理解对不对，希望大佬能指导一下😂

- 0000：第一个0X00是payload[0], 程序会进入case 0x00分支，第二个0x00是设置要填充的值，这里就是将epd_buffer(缓存了要刷到黑白屏幕显存的数据)和epd_temp(缓存了要刷到红色屏幕显存的数据)都填充为0x00
- 020000:进入0x02分支，设置当前块计数为0, （不是一次将图片全发过去，是按块发送的，先设置为0，后面每发一块数据就会加一）

**Comment by HapCoderWei** [comment]
噢~明白了，看到你的解释之后，我又去看了下浏览器中发送的代码，发现具体发送图片数据是在`sendBufferData`这个方法中，然后就和8359的代码可以对应上了。理解了，非常感谢大佬的解答，谢谢！
